platform :ios, '7.0' 

link_with [:Sample, :Tests]
pod 'SHPresenterBlocks', :path => '../'
pod 'SHTransitionBlocks'

target :Tests, :exclusive => true do
  pod 'SHTestCaseAdditions'
  pod "KIF/XCTest", :git => "https://github.com/tonyd256/KIF", :branch => "xctest"
end





